---
apiVersion: v2
appVersion: v2.12.5
description: A Python based monitoring and tracking tool for Plex Media Server
name: tautulli
version: 11.4.2
kubeVersion: ">=1.16.0-0"
keywords:
  - tautulli
  - plex
home: https://github.com/mibmal/charts/tree/main/charts/tautulli
icon: https://github.com/Tautulli/Tautulli/blob/master/data/interfaces/default/images/logo.png?raw=true
sources:
  - https://github.com/Tautulli/Tautulli
  - https://hub.docker.com/r/linuxserver/tautulli
maintainers:
  - name: mibmal
    email: michael@maley.me
dependencies:
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.5.2
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 4.5.2
